# Generated by Django 5.2.7 on 2025-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='warga',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
    ]
